@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Ship Chief Electrical Engineer" as SC
participant ":EnergyUI" as EUI
participant ":EnergyController" as EC
participant ":Company" as COMP
participant "fsiapStore: FsiapStore" as FS
participant "p: Printer" as P
participant "energy: double"
participant "segundos: int"
participant "temperature: int"

activate SC
SC -> EUI: asks to know the total energy to be supplied to the set of containers\n in a certain established trip, assuming that all the containers have the same behaviour
activate EUI
EUI -> EC : energy = getEnergy(segundos, temperature)
activate EC
EC -> COMP : fsiapStore = getFsiapStore()
activate COMP
deactivate COMP
EC -> FS : energy = getEnergyFromATripToNegativeContainer(segundos,temperature)
activate FS
deactivate FS
EC -> P : print(Energy to maintain,energy,US413)
activate P
deactivate P
deactivate EC
EUI --> SC : shows the data (energy values) and informs operation success
deactivate EUI
deactivate SC
@enduml