@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package "ui" {
class ContainersToLoadUI{
}
}

package "controllers" {
class ContainersToLoadController{
+getContainersToLoadOnNextPort(shipMMSI)
+printer(fileName, tringToPrint)
}
}
package utils{
class Printer{
+print()
}
}
package data{
class ContainersToLoad{
+getContainersToLoadOnNextPort(shipMMSI)
}
}



ContainersToLoadUI ..> ContainersToLoadController
ContainersToLoadController ..> Printer
ContainersToLoadController ..> ContainersToLoad
@enduml