@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Ship Captain" as SC
activate SC

SC -> ":System": asks to know the audit trail of a container of a cargo manifest
activate ":System"
":System" --> SC: requests data (containerNumber, ISOCode, cargoManifestID)
deactivate ":System"

SC -> ":System": types requested data
activate ":System"
":System" --> SC : shows the audit trail
deactivate ":System"

deactivate SC
@enduml