@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Port Manager" as PM
activate PM

PM -> ":System": asks for a map of the occupation of the existing resources in the port during a given month.
activate ":System"
":System" --> PM: requests data (i.e.: portId and date)
deactivate ":System"

PM -> ":System": types requested data
activate ":System"
":System" --> PM : shows the data (map) and informs operation success
deactivate ":System"

@enduml