@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Port Manager" as PM
activate PM

PM -> ":System": asks to generate, a week in advance, the loading and unloading map based on ships and trucks load manifests and corresponding travel plans
activate ":System"
":System" --> PM: requests data (i.e.: portId)
deactivate ":System"

PM -> ":System": types requested data
activate ":System"
":System" --> PM : shows the data (map) and informs operation success
deactivate ":System"

@enduml