@startuml
skinparam classAttributeIconSize 0

package "Controller"{
class MakeSummaryController
}

package "UI"{
class MakeSummaryUI
}

package "Model"{
class Ship
class Company
class ShipPosition
class Summary
}

package utils{
class Printer
package store{
class ShipStore
}
}

package BST{
class BST
}

class ShipPosition{
-MMSI
-date
-LAT
-LON
-SOG
-COG
-heading
-cargo
-transciever
+getLatitude()
+getLongitude()
}

class Ship{
-MMSI
-name
-IMO
-callsign
-type
-length
-width
-draft
+getMMSI()
+getSp()
+getVesselName()
}

class Company{
+getShipStore()
}

class BST{
+smallestElement()
+biggestElement()
+size()
+inOrder()
}

class MakeSummaryController{
+makeSummary(shipCode)
+print(summary)
}

class ShipStore{
+getShipByMMSI(MMSI)
+getShipByIMO(IMO)
+getShipByCallSign(callSign)
+getTotalMovementTime(startBaseDateTime, endBaseDateTime)
+getMaxSOG(list)
+getMeanSOG(list)
+getMaxCOG(list)
+getMeanCOG(list)
+getTravelDistance(list)
+getDeltaDistance(list)
}

class Summary{
-shipCode
-vesselName
-startBaseDateTime
-endBaseDateTime
-totalMovementTime
-totalMovements
-maxSOG
-meanSOG
-maxCOG
-meanCOG
-depLat
-depLong
-arrivalLat
-arrivalLong
-travelDistance
-deltaDistance
}

class Printer{
+print(summary)
}

MakeSummaryUI .-> MakeSummaryController
MakeSummaryController .--> Company
MakeSummaryController .--> ShipStore
Company "1"-->"1" ShipStore : Knows
ShipStore "1"->"*" Ship : registers
ShipStore "1"->"*" ShipPosition : registers
Ship "*"->"1" BST : stored
ShipStore .-> BST
Summary --> Printer
@enduml