@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TM
activate TM

TM -> ":System": asks to know the most efficient circuit that starts from a source location and\n visits the greatest number of other locations once, returning to the starting location
activate ":System"
":System" --> TM : shows the data (most efficient circuit and shortest total distance) and informs operation success
deactivate ":System"
@enduml