@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package "ui" {
class ArqcpUI{
}
}

package "controllers" {
class ArqcpController{
+arqcp(cargomanifestId)
+printer(fileName, stringToPrint)
}
}
package utils{
class Printer{
+print()
}
}

package data{
class Arqcp{
+arqcp(databaseConnection,cargomanifestId)
}
}



ArqcpUI ..> ArqcpController
ArqcpController ..> Printer
ArqcpController ..> Arqcp
@enduml