@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {

}

class Ship{
-MMSI
-name
-IMO
-callsign
-type
-length
-width
-draft
}

class ShipPosition {
   -shipMMSI
   -date
   -latitude
   -longitude
   -sog
   -cog
   -heading
   -cargo
   -transciever
}

class Port{
-id
-name
-continent
-country
-latitude
-longitude
}
TrafficManager "*" -- "1" Company : knows <
TrafficManager "1" -- "*" Ship : manages >
Company "1" -- "*" Ship : owns >
Ship "1" -- "*" ShipPosition : has >
Company "1" -- "*" Port : knows >
Port "*" -- "*" Ship : docks <

@enduml