@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Traffic Manager" as TM
activate TM

TM -> ":System": asks to see the position on a period or on a date
activate ":System"
":System" --> TM: requests data
deactivate ":System"

TM -> ":System": types requested data
activate ":System"
":System" --> TM : shows the data
deactivate ":System"

@enduml