@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Ship Chief Electrical Engineer" as SCEE
activate SCEE

SCEE -> ":System": asks to know the total energy to be supplied to the set of containers\n in a certain established trip, assuming that all the containers have the same behaviour.
activate ":System"
":System" --> SCEE : shows the data (energy values) and informs operation success
deactivate ":System"
@enduml