@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Ship Captain" as FM
activate FM

FM -> ":System": asks to know the best vessel type for the task
activate ":System"
":System" --> FM: requests data (numberOfContainers)
deactivate ":System"

FM -> ":System": types requested data
activate ":System"
":System" --> FM : shows the data and informs operation success
deactivate ":System"
@enduml