@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Client" as C
activate C

C -> ":System": asks to know the route of the container
activate ":System"
":System" --> C: requests data (clientRegistrationCode, containerNumber, ISOCode)
deactivate ":System"

C -> ":System": types requested data
activate ":System"
":System" --> C : shows the route of the container
deactivate ":System"

deactivate C
@enduml